# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
reports:
    exclude_contracts:
        - SafeMath

dependencies:
    - OpenZeppelin/openzeppelin-contracts@4.3.2
    # - Uniswap/v3-core@1.0.0
    # - Uniswap/v3-periphery@1.3.0
compiler:
    evm_version: istanbul
    solc:
        version: 0.8.4
        optimizer:
            enabled: true
            runs: 1
        remappings:
            - "@openzeppelin=/home/lenovo/.brownie/packages/OpenZeppelin/openzeppelin-contracts@4.3.2"
