# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
reports:
    exclude_contracts:
        - SafeMath

dependencies:
    - OpenZeppelin/openzeppelin-contracts@4.3.2
compiler:
    evm_version: istanbul
    solc:
        version: 0.8.4
        optimizer:
            enabled: true
            runs: 1
        remappings:
            - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2"
dotenv: .env
